### ISSUE TITLE
Acknowledge user input cannot be skipped

### ISSUE THREAD

**Issue by sebbonnet** [plannigan/columbo#487]
As of version `0.13.0.post1`, it's not possible to skip user input for interactions of type `Acknowledge`.
This makes it difficult to unit test interactions where no user interaction is possible. In fact when attempting to unit test such a scenario, the test will fail due to a time out waiting for a user input.

Would it be possible to update the `Acknowledge` interaction so it honours the `no_user_input`  property like the rest of the questions? I'm happy to submit a PR for this.

**Comment by plannigan** [comment]
Thanks for raising this issue to my attention, that was an oversight. I think it would make sense to add a `no_user_input` argument to [display()](https://github.com/plannigan/columbo/blob/b346b145a4101032ef557e7b36e2283747163fcb/columbo/_interaction.py#L70) like is done with `ask()`.

I'd appreciate a PR to address this.
